version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tmdb_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}

  frontend:
    build: ./frontend
    container_name: tmdb_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    stdin_open: true 
    tty: true