version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: tmdb_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}